apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          resources:
            requests:
              cpu: 10m
          #Prova que a aplicação está saudável
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            #Quantidade de tentativas até reiniciar o container
            periodSeconds: 10
            initialDelaySeconds: 20  
          #Proval que a aplicação está apta a receber requisições
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
            #Quantidade de tentativas até ignorar o readinessProve
            periodSeconds: 10
            initialDelaySeconds: 3  
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias
